version: "2"
services: 
  app:
    build: ./survey-app
    ports: 
      - "3000:3000"
    depends_on:
      - db
    env_file: ./database.env
  db:
    build: ./survey-db
    env_file: ./database.env

  
