FROM mysql
MAINTAINER Derek Duoba <derekduoba@gmail.com>

ENV MYSQL_ROOT_PASSWORD verysecret
ENV MYSQL_RANDOM_ROOT_PASSWORD yes
ENV MYSQL_DATABASE survey_app
ENV MYSQL_USER surveyuser
ENV MYSQL_PASSWORD every1lovessurveys

EXPOSE 3306
